-- h2 db 연동

-- member 테이블 삭제 및 생성
drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

-- member 테이블 조회 및 추가
select * from member;

insert into member(name) values('spring');
insert into member(name) values('spring2');